parameters:
  credits:
    - {title: '积分', volume: 0}
    - {title: '余额', volume: 100}

services:
#    member.example:
#        class: Modular\MemberBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
