Modular\MemberBundle\Entity\YuzhiMemberGroup:
    type: entity
    table: yuzhi_member_group
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
                comment: 分组名称
        desc:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
                comment: 分组介绍
        isDefault:
            type: integer
            nullable: true
            options:
                unsigned: false
                comment: 默认分组
            column: is_default
    lifecycleCallbacks: {  }
