
member:
    resource: "@MemberBundle/Resources/config/routing.yml"
    prefix:   /member

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: '@AppBundle/Controller/'
    type: annotation
